services:
  webapplication:
    image: ${DOCKER_REGISTRY-}webapplication
    #platform: windows
    build:
      context: .
      dockerfile: WebApplication\Dockerfile
    # depends_on:
    #   - postgres

  postgres: 
    #image: "stellirin/postgres-windows:12-1909"
    image: "postgres:15"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "just_for_test"
      POSTGRES_DB: "OTUS"
#     volumes:
#       - data:C:\Program Files\PostgreSQL\15\data

# volumes:
#   data: