@startuml
skinparam linetype ortho
left to right direction


together {

	entity "Документы" as documentation {
		* doc_id : Guid | int <<PK>>
		--
		* Название документа : string
		* Документ : binary
		--
		* doc_type_id : Guid | int
		
		event_id : Guid | int <<FK>>
		event_competition_id : Guid | int <<FK>>
		
		* Признак удаления : bool /* default = false */
	}

	entity "Категории документов (справочник)" as documentation_type {
		* doc_type_id : Guid | int <<PK>>
		--
		* Наименование: string
	}
}

together {

	entity "Мероприятие" as event {
		* event_id : Guid | int <<PK>>
		--
		* Название : string

		* Дата и время начала мероприятия : datetime
		* Дата и время окончания мероприятия : datetime
		* Дата и время начала регистрации участников : datetime
		* Дата и время окончания регистрации участников : datetime
		Дата начала контроля актуальности : datetime
		Дата окончания контроля актуальности : datetime

		Обратная связь : string

		* Публикация : bool
		* Дата регистрации: datetime
		--
		* potent_id : Guid | int <FK> /*Организатор*/
		
		* Признак удаления : bool /* default = false */
	}

	entity "Состязание мероприятия" as event_competition {
		* event_competition_id : Guid | int <<PK>>
		--
		* Название : string
		* Тип состязания: { индивидуальное | командное | смешанное }		
		* Дата и время начала состязания : datetime
		* Дата и время окончания состязания : datetime
		Минимальное количество членов команды : int
		Максимальное количество членов команды : int	

		* Публикация : bool
		* Дата регистрации: datetime
		--
		* event_id : Guid | int <<FK>>
		* potent_id : Guid | int <FK> /*Кто ввёл*/
		
		* Признак удаления : bool /* default = false */
	}

}

' На созвоне от 23.03.2025 решили, что команды будут пересоздаваться для каждого мероприятия
entity "Команда" as team {
	* team_id : Guid | int <<PK>>
	--
	* Название : string
	* Дата регистрации: datetime

	Команда согласована администрацией мероприятия: bool
	Комментарий (почему отклонена) : string
	participant_id : Guid | int <<FK>> /* Кто согласовал команду */
	--
	* potent_id : Guid | int <<FK>> /*Капитан*/
	* event_competition_id : Guid | int <<FK>>
	
	* Признак удаления : bool /* default = false */
}

together {

	entity "Потенциальный\nучастник/организатор/\nсудья/секретарь/\nкапитан" as potent {
		* potent_id : Guid | int <<PK>>
		--
		* Фамилия : string
		* Имя : string
		* Отчество : string
		* Дата рождения : date
		* Пол : bit
		* Email : string
		* Логин : string
		* Пароль : string | хэш

		* Дата регистрации: datetime
		
		* Признак удаления : bool /* default = false */
	}

	' Связь многие-ко-многим между "Мероприятием" и "Потенциальным участником"
	' А заодно - заявка на участие в конкретном состязании мероприятия
	entity "Участник мероприятия|Заявка" as participant {
		* participant_id : Guid | int <<PK>>
		--
		* id_role : Guid | int <<FK>> /* Роль */
			
		Подтверждение от капитана команды : bool
		
		* request_status_id : Guid | int <<FK>>
		* set_status_id : Guid | int <<FK>> /*Кто последним выставил статус заявки*/
		Комментарий : string

		is_actual : bool
		actual_id : Guid | int <<FK>> /*Кто подтвердил актуальность участия*/
		
		* Когда подана : datetime
		--
		* potent_id : Guid | int <<FK>> /*Чья заявка*/
		* event_competition_id : Guid | int <<FK>> /*Где участвует*/
		team_id : Guid | int <<FK>> /*Член какой команды*/
		
		* Признак удаления : bool /* default = false */
	}

	' Справочник ролей. Пока только четыре: обычный участник; главный судья; судья; секретарь
	entity "Роли участника (справочник)" as roles {
		* id_role : Guid : int <<PK>>
		--
		* Наименование : string
	}

	' Справочник статусов заявок. Пока только : подана; принята на рассмотрение; одобрена; отклонена
	entity "Статусы заявок (справочник)" as request_status {
		* request_status_id : Guid | int <<PK>>
		--
		* Наименование: string
	}
}


documentation }|..|| documentation_type
documentation ||..o| event
documentation ||..o| event_competition

event_competition }|..|| event

potent ||..|{ team
potent ||..|{ participant
potent ||..|{ event
potent ||..|{ event_competition

team }|..|| event_competition
team "participant_id" ||.up.|| participant

participant }|..|| event_competition
participant }o..|| team
participant |o....|| participant : set_status_id
participant |o....|| participant : actual_id
participant ||..|| roles
participant ||..|| request_status

@enduml