@startuml
left to right direction

actor potent as "Потенциальный\nучастник/организатор/\nсудья/секретарь"

actor organizer as "Организатор"
actor participant as "Соревнующийся"
actor secretary as "Секретарь"
actor mainSecretary as "Главный\nсекретарь"
actor judge as "Судья"
actor mainJudge as "Главный судья"

rectangle Приложение {
    usecase regEvent as "Регистрация\nмероприятия"
    usecase regCompetition as "Регистрация\nсостязания"
    usecase regTeam as "Регистрация\nкоманды"

    usecase sendRequest as "Подача\nзаявки"
    usecase considerRequest as "Рассмотрение\nзаявки"

    usecase regCompetitionResult as "Регистрация\nрезультатов\nсоревнования"

    usecase regEventResult as "Регистрация\nрезультатов\nмероприятия"

    usecase lookRequest as "Просмотр\nзаявок"
    usecase lookResult as "Просмотр\nрезультатов"
}

organizer --|> potent
participant --|> potent
secretary --|> potent
judge --|> potent

mainSecretary --|> secretary
mainJudge --|> judge

potent --- sendRequest
potent --- lookRequest
potent --- lookResult

organizer --- regEvent
organizer --- regCompetition
organizer --- regTeam
organizer --- considerRequest


regEvent ...> regTeam : include

secretary --- regCompetitionResult
judge --- regCompetitionResult

secretary --- regEventResult
judge --- regEventResult


@enduml