@startuml
left to right direction

actor anyUser as "Незарегистрированный\nпользователь"
actor user as "Зарегистрированный\nпользователь"
actor authUser as "Авторизованный\nпользователь"

rectangle Приложение {
    (Регистрация) as reg
    (Авторизация) as auth
    (Просмотр\nоткрытых\nрезультатов) as lookOpen
    (Выход) as exit
}

anyUser -- reg
user -- auth

anyUser -- lookOpen

authUser -- exit

@enduml