@startuml

state "Создана" as created
state "Подана на рассмотрение" as submitted
'Принимает или отклоняет представитель администрации мероприятия
state "Отклонена" as rejected
state "Принята" as accepted
'Отзывает податель заявки
state "Отозвана" as withdrawn

[*] --> created
created --> submitted
submitted --> rejected
submitted --> accepted
submitted --> withdrawn

accepted --> [*]
rejected --> [*]
withdrawn --> [*]

@enduml