@startuml

state "Создана" as created
state "Подана на рассмотрение" as submitted

state "Принята капитаном" as acceptedByCaptain
'Полностью принимает или отклоняет представитель администрации мероприятия
state "Принята полностью" as accepted
state "Отклонена" as rejected
'Отзывает податель заявки
state "Отозвана" as withdrawn

[*] --> created
created --> submitted
submitted --> rejected
submitted --> acceptedByCaptain
submitted --> withdrawn
acceptedByCaptain --> rejected
acceptedByCaptain --> accepted
acceptedByCaptain --> withdrawn

accepted --> [*]
rejected --> [*]
withdrawn --> [*]

@enduml