@startuml
left to right direction

actor anyone as "Посетитель"

actor potent as "Потенциальный\nучастник/организатор/\nсудья/секретарь/\nкапитан"
actor capitan as "Капитан команды"

actor organizer as "Организатор"
actor participant as "Соревнующийся"
actor secretary as "Секретарь"
actor judge as "Судья"
actor mainJudge as "Главный судья"

rectangle Приложение {
	rectangle {
		usecase regEvent as "Регистрация\nмероприятия"
		usecase regCompetition as "Регистрация\nсостязания\nмероприятия"
	}
    
	usecase requestTeam as "Заявка на\nрегистрацию команды"

	rectangle {
		usecase sendParticipantRequest as "Подача\nзаявки\nучастника"
		usecase sendJudgeRequest as "Подача\nзаявки\nсудьи"
		usecase sendSecretaryRequest as "Подача\nзаявки\nсекретаря"
		usecase withdrawRequest as "Отзыв своей заявки\n(любого типа)"
	}
	usecase deleteRequest as "Удаление своей заявки\n(любого типа)"

	usecase considerRequest as "Рассмотрение\nзаявки любого типа"
    usecase comandParticipantConfirmation as "Подтверждение\nтого, что участник\nчлен команды"
    usecase actualParticipantConfirmation as "Подтверждение\nтого, что участник\nбудет участвовать"

	rectangle {
		usecase regCompetitionResult as "Регистрация\nрезультатов\nсоревнования"
		usecase fixCompetitionResult as "Фиксация\nрезультатов\nсоревнования"
	}

	rectangle {
		usecase regEventResult as "Регистрация\nрезультатов\nмероприятия"
		usecase fixEventResult as "Фиксация\nрезультатов\nмероприятия"
	}

    usecase lookRequest as "Просмотр\nзаявок"
    usecase lookResult as "Просмотр\nрезультатов"
}

capitan --|> potent
organizer --|> potent
participant --|> potent
secretary --|> potent
judge --|> potent

mainJudge --|> judge

organizer --- regEvent
organizer --- regCompetition


potent --- sendParticipantRequest
potent --- sendJudgeRequest
potent --- sendSecretaryRequest
potent --- withdrawRequest
potent --- deleteRequest
potent --- lookRequest
potent --- lookResult

withdrawRequest .up.> sendParticipantRequest : extend
withdrawRequest .up.> sendJudgeRequest : extend
withdrawRequest .up.> sendSecretaryRequest : extend

capitan --- comandParticipantConfirmation
capitan --- requestTeam

organizer --- actualParticipantConfirmation
judge --- actualParticipantConfirmation
secretary --- actualParticipantConfirmation

organizer --- considerRequest
judge --- considerRequest
secretary --- considerRequest

secretary --- regCompetitionResult
judge --- regCompetitionResult
judge --- fixCompetitionResult

secretary --- regEventResult
judge --- regEventResult
mainJudge --- fixEventResult

anyone --- lookResult

@enduml